# Generated by Django 5.2.3 on 2026-02-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_servicos_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
